package io.appactive.db.mysql.connection.proxy;

import java.sql.Array;
import java.sql.Blob;
import java.sql.CallableStatement;
import java.sql.Clob;
import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.NClob;
import java.sql.PreparedStatement;
import java.sql.SQLClientInfoException;
import java.sql.SQLException;
import java.sql.SQLWarning;
import java.sql.SQLXML;
import java.sql.Savepoint;
import java.sql.Statement;
import java.sql.Struct;
import java.util.Map;
import java.util.Properties;
import java.util.concurrent.Executor;

import io.appactive.java.api.bridge.db.sql.SQLProtectService;

/**
 * {@linkplain Connection} proxy
 */
public class ConnectionProxy extends BaseProxy implements Connection {

    private Connection connection;

    private SQLProtectService sqlProtectService;

    public ConnectionProxy(Connection connection, Properties property,
                           SQLProtectService sqlProtectService) {
        super(property);
        this.connection = connection;
        this.sqlProtectService = sqlProtectService;
    }

    @Override
    public Statement createStatement() throws SQLException {
        return new StatementProxy(this, connection.createStatement(),property, sqlProtectService);
    }

    @Override
    public Statement createStatement(int resultSetType, int resultSetConcurrency) throws SQLException {
        return new StatementProxy(this, connection.createStatement(resultSetType, resultSetConcurrency),property, sqlProtectService);
    }

    @Override
    public Statement createStatement(int resultSetType, int resultSetConcurrency,
        int resultSetHoldability) throws SQLException {
        return new StatementProxy(this,
            connection.createStatement(resultSetType, resultSetConcurrency, resultSetHoldability),property, sqlProtectService);
    }

    @Override
    public CallableStatement prepareCall(String sql) throws SQLException {
        sqlProtectService.sqlProtect(sql, property);
        return new CallableStatementProxy(this, connection.prepareCall(sql),property,sql, sqlProtectService);
    }

    @Override
    public CallableStatement prepareCall(String sql, int resultSetType, int resultSetConcurrency) throws SQLException {
        sqlProtectService.sqlProtect(sql, property);
        return new CallableStatementProxy(this, connection.prepareCall(sql, resultSetType, resultSetConcurrency),
            property,sql, sqlProtectService);
    }

    @Override
    public CallableStatement prepareCall(String sql, int resultSetType, int resultSetConcurrency,
        int resultSetHoldability) throws SQLException {
        sqlProtectService.sqlProtect(sql, property);
        return new CallableStatementProxy(this,
            connection.prepareCall(sql, resultSetType, resultSetConcurrency, resultSetHoldability), property,sql, sqlProtectService);
    }

    @Override
    public PreparedStatement prepareStatement(String sql) throws SQLException {
        sqlProtectService.sqlProtect(sql, property);
        return new PreparedStatementProxy(this, connection.prepareStatement(sql), property,sql, sqlProtectService);
    }

    @Override
    public PreparedStatement prepareStatement(String sql, int autoGeneratedKeys) throws SQLException {
        sqlProtectService.sqlProtect(sql, property);
        return new PreparedStatementProxy(this, connection.prepareStatement(sql, autoGeneratedKeys), property,sql, sqlProtectService);
    }

    @Override
    public PreparedStatement prepareStatement(String sql, int[] columnIndexes) throws SQLException {
        sqlProtectService.sqlProtect(sql, property);
        return new PreparedStatementProxy(this, connection.prepareStatement(sql, columnIndexes), property,sql, sqlProtectService);
    }

    @Override
    public PreparedStatement prepareStatement(String sql, String[] columnNames) throws SQLException {
        sqlProtectService.sqlProtect(sql, property);
        return new PreparedStatementProxy(this, connection.prepareStatement(sql, columnNames), property,sql, sqlProtectService);
    }

    @Override
    public PreparedStatement prepareStatement(String sql, int resultSetType, int resultSetConcurrency)
        throws SQLException {
        sqlProtectService.sqlProtect(sql, property);
        return new PreparedStatementProxy(this, connection.prepareStatement(sql, resultSetType, resultSetConcurrency),
            property,sql, sqlProtectService);
    }

    @Override
    public PreparedStatement prepareStatement(String sql, int resultSetType, int resultSetConcurrency,
        int resultSetHoldability) throws SQLException {
        sqlProtectService.sqlProtect(sql, property);
        return new PreparedStatementProxy(this,
            connection.prepareStatement(sql, resultSetType, resultSetConcurrency, resultSetHoldability), property,sql, sqlProtectService);
    }

    // =========== delegate method ============

    @Override
    public Clob createClob() throws SQLException {
        return connection.createClob();
    }

    @Override
    public Blob createBlob() throws SQLException {
        return connection.createBlob();
    }

    @Override
    public NClob createNClob() throws SQLException {
        return connection.createNClob();
    }

    @Override
    public SQLXML createSQLXML() throws SQLException {
        return connection.createSQLXML();
    }

    @Override
    public boolean isValid(int timeout) throws SQLException {
        return connection.isValid(timeout);
    }

    @Override
    public void setClientInfo(String name, String value) throws SQLClientInfoException {
        connection.setClientInfo(name, value);
    }

    @Override
    public void setClientInfo(Properties properties) throws SQLClientInfoException {
        connection.setClientInfo(properties);
    }

    @Override
    public String getClientInfo(String name) throws SQLException {
        return connection.getClientInfo(name);
    }

    @Override
    public Properties getClientInfo() throws SQLException {
        return connection.getClientInfo();
    }

    @Override
    public Array createArrayOf(String typeName, Object[] elements) throws SQLException {
        return connection.createArrayOf(typeName, elements);
    }

    @Override
    public Struct createStruct(String typeName, Object[] attributes) throws SQLException {
        return connection.createStruct(typeName, attributes);
    }

    //--------------------------JDBC 4.1 -----------------------------

    @Override
    public void setSchema(String schema) throws SQLException {
        connection.setSchema(schema);
    }

    @Override
    public String getSchema() throws SQLException {
        return connection.getSchema();
    }

    @Override
    public void abort(Executor executor) throws SQLException {
        connection.abort(executor);
    }

    @Override
    public void setNetworkTimeout(Executor executor, int milliseconds) throws SQLException {
        connection.setNetworkTimeout(executor, milliseconds);
    }

    @Override
    public int getNetworkTimeout() throws SQLException {
        return connection.getNetworkTimeout();
    }

    @Override
    public boolean getAutoCommit() throws SQLException {
        return connection.getAutoCommit();
    }

    @Override
    public String getCatalog() throws SQLException {
        return connection.getCatalog();
    }

    @Override
    public int getHoldability() throws SQLException {
        return connection.getHoldability();
    }

    @Override
    public DatabaseMetaData getMetaData() throws SQLException {
        return connection.getMetaData();
    }

    @Override
    public int getTransactionIsolation() throws SQLException {
        return connection.getTransactionIsolation();
    }

    @Override
    public SQLWarning getWarnings() throws SQLException {
        return connection.getWarnings();
    }

    @Override
    public boolean isClosed() throws SQLException {
        return connection.isClosed();
    }

    @Override
    public boolean isReadOnly() throws SQLException {
        return connection.isReadOnly();
    }

    @Override
    public String nativeSQL(String sql) throws SQLException {
        return connection.nativeSQL(sql);
    }

    @Override
    public void releaseSavepoint(Savepoint savepoint) throws SQLException {
        connection.releaseSavepoint(savepoint);
    }

    @Override
    public void rollback() throws SQLException {
        connection.rollback();
    }

    @Override
    public void rollback(Savepoint savepoint) throws SQLException {
        connection.rollback(savepoint);
    }

    @Override
    public void setAutoCommit(boolean autoCommit) throws SQLException {
        connection.setAutoCommit(autoCommit);
    }

    @Override
    public void setCatalog(String catalog) throws SQLException {
        connection.setCatalog(catalog);
    }

    @Override
    public void setHoldability(int holdability) throws SQLException {
        connection.setHoldability(holdability);
    }

    @Override
    public void setReadOnly(boolean readOnly) throws SQLException {
        connection.setReadOnly(readOnly);
    }

    @Override
    public Savepoint setSavepoint() throws SQLException {
        return connection.setSavepoint();
    }

    @Override
    public Savepoint setSavepoint(String name) throws SQLException {
        return connection.setSavepoint(name);
    }

    @Override
    public void setTransactionIsolation(int level) throws SQLException {
        connection.setTransactionIsolation(level);
    }

    @Override
    public Map getTypeMap() throws SQLException {
        return connection.getTypeMap();
    }

    @Override
    public void setTypeMap(Map map) throws SQLException {
        connection.setTypeMap(map);
    }

    @Override
    public void clearWarnings() throws SQLException {
        connection.clearWarnings();
    }

    @Override
    public void close() throws SQLException {
        connection.close();
    }

    @Override
    public void commit() throws SQLException {
        connection.commit();
    }

    // ============ jdk 1.7 ==========

    @Override
    public <T> T unwrap(Class<T> iface) throws SQLException {
        T result = super.unwrap(iface);
        if (result == null) {
            result = super.unwrap(connection, iface);
        }

        return result;
    }

    @Override
    public boolean isWrapperFor(Class<?> iface) throws SQLException {
        return super.isWrapperFor(iface) || super.isWrapperFor(connection, iface);
    }

}
